### ISSUE TITLE
DOI for a STAC Collection

### ISSUE THREAD

**Issue by przell** [stac-extensions/scientific#12]
Hi,
is there a way to assign a DOI to a STAC collection? I don't want to upload it on Zenodo, and the collection is constantly growing. I guess that's a common use case for STAC collections. Are there any examples, best practices? Here's our collection, every participant of the online course [Cubes and Clouds](https://eo-college.org/courses/cubes-and-clouds/) (course starts soon) submits their results to this community map: https://esa.pages.eox.at/cubes-and-clouds-catalog/browser/#/snow_map/collection.json

**Comment by m-mohr** [comment]
I'm not sure I understand the question, but you can use sci:doi in a Collection. It's up to you to register the DOI.

**Comment by przell** [comment]
> but you can use sci:doi in a Collection.

I understood that the sci:doi is for the DOI of the scientific publication that is related to the collection.

> It's up to you to register the DOI.

That would be my question how to register a DOI for a STAC collection that is constantly growing. For example this S2 collection is also adding images daily. The collection doesn't have a DOI itself. Are there are any examples of a STAC collection that has its own DOI you or the STAC community knows of?

**Comment by m-mohr** [comment]
The registration of DOIs for STAC resources is not in scope of STAC and up to the user.

You could potentially bring this up as a discussion item in stac-spec ( https://github.com/radiantearth/stac-spec/discussions )  to gather feedback but it's not really an issue of this extension, so closing here. Also, isn't EURAC working on that eventually? (-> Alex/Fabricio)
