### ISSUE TITLE
Deprecate in favor of CFF?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/scientific#3]
It seems that CFF ( https://citation-file-format.github.io/ ) is the new upcoming thing that people may use and is pushed by GitHub.
I'm wondering whether it may make sense to deprecate our own "proprietary" extension and instead use CFF or link to it?
A less disruptive way would just to specify how to link to it.

**Comment by matthewhanson** [comment]
Discussed in STAC sprint.  
Decided this should not be deprecated in favor of CFF files.  However, CFF files may be useful to include as links with a rel type of `cite-as`.
