### ISSUE TITLE
Generalize scientific extension to STAC catalogs

### ISSUE THREAD

**Issue by KennSmithDS** [stac-extensions/scientific#6]
Since Collections inherit properties from Catalogs, it makes sense to generalize extensions like `sci:...` to be able to be used in Catalogs, as well as Collections.

**Comment by m-mohr** [comment]
Would you be open to create a PR for it?
I also did it recently for timestamps and you could take it as a baseline if you want:
https://github.com/stac-extensions/timestamps/commit/02da21e48c36bb72a4110c4e39b5ba67f8715d55
